name: CI
on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    steps:
      - name: build
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_KEY: ${{ secrets.DATABASE_KEY }}